---

- name: Configure iocage
  hosts: localhost
  connection: local
  gather_facts: false
  # become: true
  # become_method: sudo

  vars_files:

    - vars/iocage_task_db.yml

  vars:

    lbr: "{{ '{{' }}"
    rbr: "{{ '}}' }}"
    tests: [facts, fetch,
            base_create, base_exists, base_set, base_clone,
            jail_absent, jail_restore,
            template_create, template_stop, template_start,
            absent_absent, absent_stop, absent_restart, absent_start,
            test_present, test_absent, test_clone, test_start, test_start2, test_exec,
            test_restart, test_stop, test_start3, test_absent2, test_absent3, test_pkg]

  tasks:

    - name: Create test files in directory tasks
      ansible.builtin.template:
        src: '{{ iocage_task_db[item].template }}.j2'
        dest: '{{ playbook_dir }}/tasks/{{ item }}.yml'
        mode: '0664'
        backup: true
        validate: ansible-lint %s
      loop: '{{ tests }}'
      vars:
        task: '{{ iocage_task_db[item] }}'
      tags: create_tasks
