---

- name: Configure iocage
  hosts: localhost
  connection: local
  gather_facts: false
  # become: true
  # become_method: sudo

  vars_files:

    - vars/iocage_test_db.yml
    - vars/iocage_group_db.yml

  vars:

    lbr: "{{ '{{' }}"
    rbr: "{{ '}}' }}"
    tests: "{{ iocage_test_db.keys()|list }}"
    test_groups: "{{ iocage_group_db.keys()|list }}"

  tasks:

    - name: Create test files in directory tasks
      ansible.builtin.template:
        src: '{{ iocage_test_db[item].template }}.j2'
        dest: '{{ playbook_dir }}/tasks/{{ item }}.yml'
        mode: '0664'
        backup: true
        validate: ansible-lint %s
      loop: '{{ tests }}'
      vars:
        test: '{{ iocage_test_db[item] }}'
      tags: create_tasks

    - name: Create group files in directory tasks
      ansible.builtin.template:
        src: '{{ iocage_group_db[item].template }}.j2'
        dest: '{{ playbook_dir }}/tasks/{{ item }}.yml'
        mode: '0664'
        backup: true
        validate: ansible-lint %s
      loop: '{{ test_groups }}'
      vars:
        group: '{{ iocage_group_db[item] }}'
      tags: create_groups

    - name: Create playbook iocage_test.yml
      ansible.builtin.template:
        src: iocage_test.yml.j2
        dest: iocage_test.yml
        mode: '0664'
        backup: true
        validate: ansible-lint %s
      tags: create_iocage_test
