---

- hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo

  vars:

    python_required: "36"
    jname: test_jail
    release: 13.0-RELEASE
    label: 13_0_RELEASE
    basejail: "test_basejail_{{ label }}"
    debug: false
    debug2: false

  tasks:

      # setup - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/sanity.yml
      tags: sanity
    - ansible.builtin.import_tasks: tasks/facts.yml
      tags: facts
    - ansible.builtin.import_tasks: tasks/fetch.yml
      tags: fetch

      # base - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/base_create.yml
      tags: base_create
    - ansible.builtin.import_tasks: tasks/base_exists.yml
      tags: base_exists
    - ansible.builtin.import_tasks: tasks/base_set.yml
      tags: base_set
    - ansible.builtin.import_tasks: tasks/base_clone.yml
      tags: base_clone

      # jail - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/jail_absent.yml
      tags: jail_absent
    - ansible.builtin.import_tasks: tasks/jail_restore.yml
      tags: jail_restore

      # template - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/template_create.yml
      tags: template_create
    - ansible.builtin.import_tasks: tasks/template_start.yml
      tags: template_start
    - ansible.builtin.import_tasks: tasks/template_start_force.yml
      tags: template_start_force
    - ansible.builtin.import_tasks: tasks/template_stop.yml
      tags: template_stop

      # absent - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/absent_absent.yml
      tags: absent_absent
    - ansible.builtin.import_tasks: tasks/absent_stop.yml
      tags: absent_stop
    - ansible.builtin.import_tasks: tasks/absent_restart.yml
      tags: absent_restart
    - ansible.builtin.import_tasks: tasks/absent_start.yml
      tags: absent_start

      # test everything - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    - ansible.builtin.import_tasks: tasks/test_present.yml
      tags: [test_present, test_all]
    - ansible.builtin.import_tasks: tasks/test_absent.yml
      tags: [test_absent, test_all]
    - ansible.builtin.import_tasks: tasks/test_clone.yml
      tags: [test_clone, test_all]
    - ansible.builtin.import_tasks: tasks/test_pkg.yml
      tags: [test_pkg, test_all]
    - ansible.builtin.import_tasks: tasks/test_start.yml
      tags: [test_start, test_all]
    - ansible.builtin.import_tasks: tasks/test_start2.yml
      tags: [test_start2, test_all]
    - ansible.builtin.import_tasks: tasks/test_exec.yml
      tags: [test_exec, test_all]
    - ansible.builtin.import_tasks: tasks/test_restart.yml
      tags: [test_restart, test_all]
    - ansible.builtin.import_tasks: tasks/test_stop.yml
      tags: [test_stop, test_all]
    - ansible.builtin.import_tasks: tasks/test_start3.yml
      tags: [test_start3, test_all]
    - ansible.builtin.import_tasks: tasks/test_absent2.yml
      tags: [test_absent2, test_all]
    - ansible.builtin.import_tasks: tasks/test_absent3.yml
      tags: [test_absent3, test_all]
