#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright 2015, Perceivon Hosting Inc.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY [COPYRIGHT HOLDER] AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL [COPYRIGHT HOLDER] OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import sys
import re

DOCUMENTATION = """
---
module: 
version_added:
short_description: FreeBSD iocell jail handling
description:
    - The M(iocell) module allows several iocell commands to be executed through ansible.
    - document use-cases here
options:
    state:
      description:
          - state of the desired result
      choices: ['basejail', 'template', 'cloned', 'started', 'stopped', 'restarted', 'fetched', 'exec', 'pkg', 'exists', 'absent', 'set']
      required: true
      default: exec
    tag:
      description:
          - tag of the new jail
      required: false
    uuid:
      description:
          - uuid of the jail
      required: false
author: xmj
"""

EXAMPLES = """
# create basejail:
- iocell: state=basejail tag="foo"

# create template:
- iocell: state=template tag="foo" clone_from="basejail_10.2-BETA1" properties="ip4_addr='lo1|10.1.0.5' boot=on allow_sysvipc=1 pkglist=/path/to/pkglist.txt defaultrouter='10.1.0.1'

# clone existing jail:
- iocell: state=cloned tag="foo" clone_from="05a32718-2de2-11e5-ad68-a710c4a2a00f" properties="ip4_addr='lo1|10.1.0.5' boot=on allow_sysvipc=1 pkglist=/path/to/pkglist.txt defaultrouter='10.1.0.1'

# start existing jail:
- iocell: state=started uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f"

# stop existing jail:
- iocell: state=stopped uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f"

# restart existing jail:
- iocell: state=restarted uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f"

# execute command in (running) jail:
- iocell state=exec uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f" cmd="service sshd start"

# execute pkg command in (running) jail:
- iocell state=pkg uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f" cmd="service sshd start"

# force destroy jail
- iocell state=absent uuid="05a32718-2de2-11e5-ad68-a710c4a2a00f"
"""

def _jail_started(module, iocell_path='/usr/local/sbin/iocell', argument=None, assume_stopped=False):
    cmd = "%s get state %s" % (iocell_path, argument)
    rc, state, err = module.run_command(cmd)

    if state.strip() == 'up' and assume_stopped:
        module.fail_json(msg="Jail {0} is already running.".format(argument))

    _msg = "Jail {0} running : '{1}'".format(argument, argument)
    if state.strip() == 'up':
        return True
    return False

def jail_exists(module, iocell_path='/usr/local/sbin/iocell', argument=None, assume_absent=False):
    cmd = "%s get host_hostuuid %s" % (iocell_path, argument)
    rc, uuid, err = module.run_command(cmd)
    _msg = ""
    if uuid and assume_absent:
        module.fail_json(msg="Jail {0} already exists.".format(argument))
    if not rc == 0 and not assume_absent:
        uuid = "-"
        module.fail_json(msg="Jail {0} does not exist.".format(argument))
    if not rc == 0 and assume_absent:
        uuid = "-"
        _msg = "Jail {0} does not exist.".format(argument)
    else:
        _msg = "Jail {0} exists with uuid: {1}".format(argument, uuid)
    return uuid.strip(), False, _msg

def jail_start(module, iocell_path='/usr/local/sbin/iocell', argument=None, force=None):
    uuid, _, _ = jail_exists(module, iocell_path, argument, False)

    cmd = "%s start %s" % (iocell_path, argument)
    if force == "yes":
        cmd = "%s start -f %s" % (iocell_path, argument)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        _started = _jail_started(module, iocell_path, argument, False)
        if not _started and not uuid == "-":
            rc, out, err = module.run_command(cmd)
            if not rc == 0:
                module.fail_json(msg="Jail {0} could not be started.\nstdout:\n{1}\nstderr:\n{2}".format(argument, out, err))
            _msg = "Jail {0} was started.\n{1}".format(argument,out)
            _changed = True
        elif not _started and uuid == "-":
            module.fail_json(msg="Jail '{0}' does not exist.".format(argument, uuid))
        elif _started:
            _msg = "Jail {0} is already running.".format(uuid)
            _changed = False

    uuid, _, _ = jail_exists(module, iocell_path, argument, False)
    return uuid, _changed, _msg

def _release_exists(module, iocell_path='/usr/local/sbin/iocell', release="10.3-RELEASE"):
    release_path = "/iocell/releases/%s/root"
    cmd = "%s list -r | grep %s" % (iocell_path, release)
    rc = 1
    rc, out, err = module.run_command('/bin/sh -c "%s"' % cmd)
    if not rc == 0:
        return False
    return True

def release_fetch(module, iocell_path='/usr/local/sbin/iocell', release="10.3-RELEASE", update=False):
    _exists = _release_exists(module, iocell_path, release)
    _changed = False

    if _exists and not update:
        _msg =  "Release %s already present." % release
    else:
        if not module.check_mode:
            cmd = "%s fetch release=%s" % (iocell_path, release)
            rc = 1
            rc, out, err = module.run_command(cmd)
            if not rc == 0:
                module.fail_json(msg="Release {0} could not be fetched.\nstdout:\n{1}\nstderr:\n{2}".format(release, out, err))
            _changed = True
            if _exists and update:
                 _msg = "Release {0} was successfully updated.".format(release)
            elif not _exists:
                 _msg = "Release {0} was successfully fetched.".format(release)

    return _changed, _msg


def jail_restart(module, iocell_path='/usr/local/sbin/iocell', argument=None):
    uuid, _, _ = jail_exists(module, iocell_path, argument, False)
    cmd = "%s restart %s" % (iocell_path, uuid)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        if not uuid == "-":
            rc, out, err = module.run_command(cmd)
            if not rc == 0:
                module.fail_json(msg="Jail {0} could not be restarted.\nstdout:\n{1}\nstderr:\n{2}".format(uuid, out, err))
            _changed = True
            _msg = "Jail {0} was restarted.\n{1}".format(argument,out)
        else:
            module.fail_json(msg="Jail '{0}' does not exist.".format(argument, uuid))

    return uuid, _changed, _msg

def jail_stop(module, iocell_path='/usr/local/sbin/iocell', argument=None):
    uuid, _, _ = jail_exists(module, iocell_path, argument, False)
    cmd = "{0} stop {1}".format(iocell_path, argument)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        _started = _jail_started(module, iocell_path, argument, False)
        if _started and argument:
            rc, out, err = module.run_command(cmd)
            if not rc == 0:
                module.fail_json(msg="Jail {0} could not be stopped.\nstdout:\n{1}\nstderr:\n{2}".format(argument, out, err))
            _msg = "Jail {0} was stopped.\n".format(argument,out)
            _changed = True
        elif not _started and argument:
            _msg = "Jail {0} is already stopped.".format(argument)
            _changed = False
        else:
            module.fail_json(msg="Jail '{0}' does not exist.".format(argument, argument))


    return uuid, _changed, _msg

def jail_exec(module, iocell_path='/usr/local/sbin/iocell', argument=None, user="root", cmd='/usr/bin/true'):
    _changed = False
    rc = 1
    out = ""
    err = ""
    _msg = ""
    if not module.check_mode:
        if _jail_started(module, iocell_path, argument, False):
            rc, out, err = module.run_command("{0} exec -U {1} {2} {3}".format(iocell_path, user, argument, cmd))

            if not rc == 0:
                module.fail_json(msg="Command '{0}' could not be executed in jail '{1}'.\nstdout:\n{2}\nstderr:\n{3}".format(cmd, argument, out, err))

            _changed = True
            _msg = "Command '{0}' was executed in jail '{1}'.\nstdout:\n{2}\nstderr:\n{3}".format(cmd, argument, out, err)
        else:
            module.fail_json(msg="Jail '{0}' is not running.".format(argument))

    return argument, _changed, _msg, out, err

def jail_pkg(module, iocell_path='/usr/local/sbin/iocell', argument=None, cmd='info'):
    _changed = False
    rc = 1
    out = ""
    err = ""
    _msg = ""
    if not module.check_mode:
        if _jail_started(module, iocell_path, argument, False):
            rc, out, err = module.run_command("{0} pkg {1} {2}".format(iocell_path, argument, cmd))

            if not rc == 0:
                module.fail_json(msg="pkg '{0}' could not be executed in jail '{1}'.\nstdout:\n{2}\nstderr:\n{3}".format(cmd, argument, out, err))

            _changed = True
            _msg = "pkg '{0}' was executed in jail '{1}'.\nstdout:\n{2}\nstderr:\n{3}".format(cmd, argument, out, err)
        else:
            module.fail_json(msg="Jail '{0}' is not running.".format(argument ))

    return argument, _changed, _msg, out, err

def jail_set(module, iocell_path='/usr/local/sbin/iocell', argument=None, properties=''):
    uuid, _, _ = jail_exists(module, iocell_path, argument, False)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    cmd = ""
    regexp = r"(\w+=(\w+|\'[^\']*\'))(?: )?"
    _properties = re.split(regexp, properties)[1::3]
    for _property in _properties:
        try:
            k, v = _property.split('=')
        except Exception as err:
            module.fail_json(msg="Attributes could not be set {0} because {1}".format(_property, sys.exc_info()))
        # XXX: maybe a little inconsistent
        cmd += "{0} set {1}={2} {3} ; ".format(iocell_path, k, v, argument)
    if not module.check_mode:
        rc, out, err = module.run_command('/bin/sh -c "%s"' % cmd)

        if not rc == 0:
            module.fail_json(msg="Attributes could not be set on jail '{0}'.\nstdout:\n{1}\nstderr:\n{2}".format(argument, out, err))

        _changed = True
        _msg = "Attributes {0} were set on jail '{1}'.".format(_properties ,argument)
    return argument, _changed, _msg

def jail_create_basejail(module, iocell_path='/usr/local/sbin/iocell', tag=None, release="10.3-RELEASE"):
    cmd = "{0} create tag={1} release={2}".format(iocell_path, tag, release)
    #module.fail_json(msg="{0}".format(cmd))
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        rc, out, err = module.run_command(cmd)
        if not rc == 0:
            module.fail_json(msg="Basejail {0} could not be created.\nstdout:\n{1}\nstderr:\n{2}".format(tag, out, err))
        _changed = True
        _msg = "Basejail {0} was created.".format(tag)
    uuid, _, _ = jail_exists(module, iocell_path, tag, False)
    return uuid, _changed, _msg

def jail_create_clone(module, iocell_path='/usr/local/sbin/iocell', clone_from_uuid=None, tag=None, properties=""):
    cmd = "{0} clone {1} tag={2} {3}".format(iocell_path, clone_from_uuid, tag, properties)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        rc, out, err = module.run_command(cmd)

        if not rc == 0:
            module.fail_json(msg="Jail '{0}' could not be cloned from '{1}'.\nstdout:\n{2}\nstderr:\n{3}".format(tag, clone_from_uuid, out, err))

        _changed = True
        _msg = "Jail '{0}' was cloned from '{1}' with properties {2}.\n\n{3}".format(tag, clone_from_uuid, properties, cmd)
        uuid, _, _ = jail_exists(module, iocell_path, tag, False)
    return uuid, _changed, _msg

def jail_destroy(module, iocell_path='/usr/local/sbin/iocell', argument=None):
    uuid, _, _ = jail_exists(module, iocell_path, argument, False)
    _changed = False
    rc = 1
    out = ""
    _msg = ""
    if not module.check_mode:
        if not uuid == "-":
            rc, out, err = module.run_command("{0} destroy -f {1}".format(iocell_path, argument))
            if not rc == 0:
                module.fail_json(msg="Jail '{0}' could not be destroyed.\nstdout:\n{1}\nstderr:\n{2}".format(argument, out, err))

            _changed = True
            _msg = "Jail '{0}' was destroyed.".format(argument)
            jail_exists(module, iocell_path, argument, True)
        else:
            module.fail_json(msg="Jail '{0}' does not exist.".format(argument))

    return None, _changed, _msg

def main():
    module = AnsibleModule(
            argument_spec    = dict(
                state        = dict(default="exec", choices=["basejail", "template", "cloned", "started", "stopped", "restarted", "fetched", "exec", "pkg", "exists", "absent", "set"], required=False),
                uuid         = dict(default="", required=False),
                stdout         = dict(default="", required=False),
                stderr         = dict(default="", required=False),
                tag          = dict(default="", required=False),
                properties   = dict(default="", required=False),
                force        = dict(default="", required=False),
                user         = dict(default="", required=False),
                cmd          = dict(default="", required=False),
                clone_from   = dict(default="", required=False),
                release      = dict(default="", required=False),
                update       = dict(default="", required=False)),
    )

    iocell_path = module.get_bin_path('iocell', True)

    p = module.params

    uuid = p["uuid"]
    tag = p["tag"].replace('.', '')
    properties = p["properties"]
    force = p["force"]
    cmd = p["cmd"]
    clone_from= p["clone_from"].replace('.', '')
    user = p["user"] or "root"
    release = p["release"]
    update = p["update"]

    jail_identifier = (uuid or tag)

    msgs = []
    changed = False
    out = ""
    err = ""

    if p["state"] == "started":
        uuid, _, _ = jail_exists(module, iocell_path, jail_identifier, False)
        uuid, changed, _msg = jail_start(module, iocell_path, jail_identifier, force)
        msgs.append(_msg)

    elif p["state"] == "stopped":
        uuid, _, _ = jail_exists(module, iocell_path,  jail_identifier, False)
        uuid, changed, _msg = jail_stop(module, iocell_path, jail_identifier)
        msgs.append(_msg)

    elif p["state"] == "restarted":
        uuid, _, _ = jail_exists(module, iocell_path,  jail_identifier, False)
        uuid, changed, _msg = jail_restart(module, iocell_path, jail_identifier)
        msgs.append(_msg)

    elif p["state"] == "exists":
        uuid, _, _msg = jail_exists(module, iocell_path,  jail_identifier, False)
        msgs.append(_msg)

    elif p["state"] == "basejail":
        uuid, _, _ = jail_exists(module, iocell_path, tag, assume_absent=True)
        if uuid == "-":
            uuid, changed, _msg = jail_create_basejail(module, iocell_path,  tag, release)
            msgs.append(_msg)

    elif p["state"] == "fetched":
        changed, _msg = release_fetch(module, iocell_path, release, update)
        msgs.append(_msg)

    elif p["state"] == "set":
        uuid, _, _ = jail_exists(module, iocell_path, tag, False)
        _, changed, _msg = jail_set(module, iocell_path, jail_identifier, properties)

    elif p["state"] == "template":
        uuid, _, _ = jail_exists(module, iocell_path, tag, True)

        if uuid == "-":
            uuid, changed, _msg = jail_create_basejail(module, iocell_path,  tag, release)
            msgs.append(_msg)
            if not changed:
                module.fail_json(msg="Jail '{0}' could not be created: {1}".format(tag, uuid))
            _, changed, _msg = jail_set(module, iocell_path, tag, properties='istemplate=yes')
            msgs.append(_msg)
            if not changed:
                module.fail_json(msg="Jail '{0}' could not be set as template: {1}".format(tag, uuid))
            if properties != "":
                _, changed, _msg = jail_set(module, iocell_path, tag, properties)
                msgs.append(_msg)
                if not changed:
                    module.fail_json(msg="Jail '{0}' could not be set with properties: {1}\nAlso, here's msg: {2}".format(tag, properties, "\n".join(msgs)))
        else:
            module.fail_json(msg="Jail '{0}' could not be created: {1}".format(tag, uuid))

    elif p["state"] == "cloned":
        clone_from_uuid, _, _ = jail_exists(module, iocell_path, (uuid or clone_from))
        tag_uuid, _, _ = jail_exists(module, iocell_path, tag, True)
        if not tag_uuid or tag_uuid == "-":
            uuid, changed, _msg = jail_create_clone(module, iocell_path, clone_from, tag, properties)
            msgs.append(_msg)
        else:
            uuid = tag_uuid

    elif p["state"] == "exec":
        _, _, _ = jail_exists(module, iocell_path, jail_identifier)
        uuid, changed, _msg, out, err = jail_exec(module, iocell_path, jail_identifier, user, cmd)
        msgs.append(_msg)

    elif p["state"] == "pkg":
        uuid, _, _ = jail_exists(module, iocell_path, jail_identifier)
        uuid, changed, _msg, out, err = jail_pkg(module, iocell_path, jail_identifier, cmd)
        msgs.append(_msg)

    elif p["state"] == "absent":
        uuid, changed, _msg = jail_destroy(module, iocell_path, jail_identifier)
        msgs.append(_msg)

    uuid = uuid or "-"
    module.exit_json(changed=changed, msg=", ".join(msgs), uuid=uuid, stdout=out, stderr=err)

# import module snippets
from ansible.module_utils.basic import *

main()
