---
- name: "Check if test_basejai_{{ label }} can be created"
  block:
    - name: "Check if test_basejai_{{ label }} can be created"
      iocage:
        state: basejail
        name: "{{ basejail }}"
        release: "{{ release }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
