---
- name: Check if basejail can be cloned
  block:
    - name: Check if basejail can be cloned
      iocage:
        state: cloned
        name: "{{ jname }}"
        clone_from: "test_basejail_{{ label }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
