---
- name: Verify that base jail can be converted
  block:
    - name: Verify that base jail can be converted
      iocage:
        state: set
        name: "{{ basejail }}"
        properties:
          template: 'no'
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
