---
- set_fact:
    _crash: true

- block:
    - name: "Check if release {{ release }} exists"
      iocage:
        state: fetched
        release: "{{ release }}"
      register: result
    - set_fact:
        _crash: false
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
    - ansible.builtin.import_tasks: custom_stats_crash.yml

- block:
    - assert:
        that:
          - result.msg is search(release)
          - not result.changed
          - not result.failed
          - result.stderr_lines|length == 0
          - result.stdout_lines|length == 0
    - ansible.builtin.import_tasks: custom_stats_pass.yml
  rescue:
    - debug:
        msg: "[ERR] {{ _test_name }} failed."
      when: debug|bool
    - ansible.builtin.import_tasks: custom_stats_fail.yml
  when: not _crash
