---
- name: Check if cloned test jail can be destroyed
  block:
    - name: Check if cloned test jail can be destroyed
      iocage:
        state: absent
        name: "{{ jname }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
