---
- name: Verify that base jail can be converted back
  block:
    - name: Verify that base jail can be converted back
      iocage:
        state: set
        name: "{{ basejail }}"
        properties:
          template: true
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
