---
- name: Check if template jail can be stopped
  block:
    - name: Check if template jail can be stopped
      iocage:
        state: stopped
        name: "test_template_{{ label }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result
