---
- name: Check if test jail can be restarted
  block:
    - iocage:
        state: restarted
        name: "{{ jname }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 in result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }}"
  vars:
    _msg1: "Jail {{ jname }} was restarted."
