---
- name: Check if test jail can be destroyed
  block:
    - name: Check if test jail can be destroyed
      iocage:
        state: absent
        name: "{{ jname }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 == result.msg or _msg2 == result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }} or {{ _msg2 }}"
  vars:
    _msg1: "Jail '{{ jname }}' was destroyed., Jail {{ jname }} removed from iocage_jails."
    _msg2: "Jail {{ jname }} is already absent."
