---
- name: Check if template jail can be destroyed
  block:
    - iocage:
        state: absent
        name: "test_template_{{ label }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 in result.msg or _msg2 == result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }} or {{ _msg2 }}"
  vars:
    _msg1: "Jail 'test_template_{{ label }}' was destroyed., Jail test_template_{{ label }} removed from iocage_templates."
    _msg2: "Jail test_template_{{ label }} is already absent."
