---
# Ansible managed

- ansible.builtin.set_fact:
    _crash: true

- block:
    - name: "test_exec: Check if exec works in jail {{ jname }}"
      iocage:
        {
          "cmd": "\"/bin/ls -la /root\"",
          "name": "{{ jname }}",
          "state": "exec"
        }
      register: result
    - ansible.builtin.set_fact:
        _crash: false
    - ansible.builtin.debug:
        var: result
      when: debug2|bool
    - ansible.builtin.debug:
        var: result.msg
      when: debug|bool
  rescue:
    - ansible.builtin.debug:
        var: ansible_failed_result
      when: debug|bool
    - ansible.builtin.import_tasks: custom_stats_crash.yml

- block:
    - ansible.builtin.assert:
        success_msg: "{{ _test_name }}: All assertions passed"
        that:
          - _msg1 in result.msg
    - ansible.builtin.import_tasks: custom_stats_pass.yml
  rescue:
    - ansible.builtin.debug:
        msg: "[ERR] {{ _test_name }} failed. Missing: {{ _msg1 }}"
      when: debug|bool
    - ansible.builtin.import_tasks: custom_stats_fail.yml
  vars:
    _msg1: "rc: 0"
  when: not _crash
