---
- name: Check if exec works in test jail
  block:
    - name: Check if exec works in test jail
      iocage:
        state: exec
        name: "{{ jname }}"
        cmd: "/bin/ls -la /root"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 in result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }}. This message should never be displayed.
               Rescue should catch the error in the block. "
  vars:
    _msg1: "rc: 0"
