---
- name: Check if test jail can be stopped
  block:
    - iocage:
        state: stopped
        name: "{{ jname }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 in result.msg or _msg2 == result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }} or {{ _msg2 }}"
  vars:
    _msg1: "Jail {{ jname }} was stopped."
    _msg2: "Jail {{ jname }} already stopped"
