---
- name: Check if test jail can be created
  block:
    - name: Check if test jail can be created
      iocage:
        state: present
        name: "{{ jname }}"
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 in result.msg or _msg2 == result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }} or {{ _msg2 }}"
  vars:
    _msg1: "Jail 'test_jail' was created with properties {}."
    _msg2: "test_jail already exists"
