---
- name: Check if pkg info does not work in not-started test jail
  block:
    - name: Check if pkg info does not work in not-started test jail
      iocage:
        state: pkg
        name: "{{ jname }}"
        cmd: info
      register: result
    - debug:
        var: result
      when: debug|bool
  rescue:
    - debug:
        var: ansible_failed_result

- assert:
    that: _msg1 == result.msg
    fail_msg: "[ERR] Missing: {{ _msg1 }}"
  vars:
    _msg1: "Jail 'test_jail' not running"
